### ISSUE TITLE
Hostname is example.com when created by operator

### ISSUE THREAD

**Issue by rockiee281** [kubevela/samples#26]
After run this example on AliCloud , I found ingress `service-tracker-ui-trait-ingress`  created with wrong hostname `example.com`

**Comment by olegchorny** [comment]
Looks like this issue is due to the wrong (outdated?) definition of ingress trait https://github.com/oam-dev/samples/blob/master/2.ServiceTracker_App/ApplicationConfiguration/tracker-app-config.yaml

It works as expected in case of:
```
      traits:
        - name: ingress
          properties:
            hostname: servicetracker.oam.io
            path: /
            servicePort: 8080
```
And current sample provides the different approach:
```
      traits:
        - name: ingress
          parameterValues:
            - name: hostname
              value: servicetracker.oam.io
            - name: path
              value: / 
            - name: service_port
              value: 8080
```
